version: "3.7"
services:
  api_service:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
      - ./api/:/usr/api/
      - ./.git/:/usr/git/
    ports:
      - 5000:5000
    depends_on:
      - db_service
    environment:
      DB_CONN_STRING: mongodb://db_service:27017/
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  db_service:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  web_service:
    build:
      context: ./web/git_wrapper/
      dockerfile: Dockerfile
    volumes:
      - ./web/git_wrapper/:/usr/web/
    ports:
      - 3000:3000
