version: "3.7"
services:
  api_service:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
      - ./api/:/usr/api/
      - ./.git/:/usr/git/
    ports:
      - 5000:5000
  web_service:
    build:
      context: ./web/git_wrapper/
      dockerfile: Dockerfile
    volumes:
      - ./web/git_wrapper/:/usr/web/
    ports:
      - 3000:3000
